blogs/urls.py
from django.urls import path

from blogs.apps import BlogsConfig
from blogs.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogsConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('list/', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('blogs.urls', namespace='list')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import home, contacts, ProductListView, ProductDetailView, ProductCreatelView, ProductUpdatelView, \
    ProductDeleteView

app_name = MainConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product'),
    path('product/create/', ProductCreatelView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', ProductUpdatelView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserVerificationView, delete

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verification/', UserVerificationView.as_view(), name='verification'),
    path('resert/', delete, name='resert'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from main.models import NULLABLE


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='email')
    phone = models.CharField(max_length=20, verbose_name='номер телефонв', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар')
    country = models.CharField(max_length=20, verbose_name='страна', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from main.forms import StyleForMixin
from users.models import User


class UserForm (StyleForMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

class VerificationForm(forms.Form):
    key = forms.CharField()

users/views.py
from django.conf import settings
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, FormView
from users.forms import UserForm, VerificationForm
from users.models import User
import random
import string
import copy


random_key = ''.join(random.choices(string.ascii_letters + string.digits, k=8))
_key = copy.copy(random_key)


class LoginView(BaseLoginView):
    template_name = 'users/login.html'

class LogoutView(BaseLogoutView):
    pass

class RegisterView(CreateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:verification')
    template_name = 'users/register.html'

    def form_valid(self, form):
        self.object = form.save()
        verification_link = "http://127.0.0.1:8000/users/register/users/verification/"

        send_mail(
            subject='Поздравляем с регистрацией',
            message= f'Для завершения регистрации перейдите по ссылке: {verification_link} \n'
                     f'Для прохождения верификации скопируйте ключ: {_key}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.object.email]
        )
        return super().form_valid(form)


class UserVerificationView(FormView):
    form_class = VerificationForm
    success_url = reverse_lazy('main:home')
    template_name = 'users/user_verification.html'

    def post(self, request, *args, **kwargs):
        key_post = request.POST.get('key_post')
        if _key == key_post:
            return redirect ('users:login')
        else:
            return render(request, 'users/user_verification.html', {'error_message': 'Ключи не совпадают'})

def delete_user(email):
    User.objects.get(email=User.email).delete()
    return redirect('home')

def delete(request):

    if request.method == "POST":
        email = request.POST.get('email')
        print(email)
        # КАКТО УДАЛИТЬ ЭКЗЕМПЛЯР КЛАССА ПРОБУЮ ЧЕРЕЗ delete_user() НО НЕ ПОЛУЧАЕТСЯ
        # delete_user(email)
        # ПРИ УСПЕШНОМ УЛАДЕННИИ ПЕРЕЙТИ НА "users:verification"
    return render(request, 'users/user_detail.html')

users/templates/users/login.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Вход</button>
                        <br>
                        <a href="{% url 'users:resert' %}" type="submit">Забыли пароль?</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/login_confirm_delete.html
{% extends 'main/base.html' %}
{% load my_tags %}

{% block content %}
<h2>Login</h2>
  {% csrf_token %}
  <p>Are you sure you want to delete the user with email: {{ email }}?</p>
  <form action="{% url 'users:delete' pk=object.pk %}" method="POST">
      {% csrf_token %}
      <button type="submit">Delete</button>
  </form>
{% endblock %}

users/templates/users/password_reset_email.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

{% autoescape off %}
Добро пожаловать!

Получено заявление на сброс вашего пароля для учетной записи с этим адресом электронной почты.

Если вы не запрашивали сброс пароля, проигнорируйте это письмо.

Чтобы сбросить пароль, щелкните на следующую ссылку:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Спасибо за использование нашего сервиса!

С уважением,
Команда поддержки
{% endautoescape %}
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Регистрация</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        <div class="form-group">
            <label for="email">Введите email:</label><br>
            <input type="text" id="email" name="email" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Восстановить</button>
    </form>

{% endblock %}

users/templates/users/user_verification.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

<body>
    <h1>Подтверждение аккаунта</h1>
    <p>Спасибо за регистрацию! Для завершения процесса создания учетной записи, пожалуйста, введите 8-ми значный ключ из письма:</p>

    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        <div class="form-group">
            <label for="key_post">Код подтверждения:</label><br>
            <label class="btn btn-danger">{{error_message}}</label>
            <input type="text" id="key_post" name="key_post" class="form-control" placeholder="Ключ из письма" required>
        </div>
        <button type="submit" class="btn btn-success">Отправить</button>
    </form>
</body>
{% endblock %}