config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('blogs.urls', namespace='list')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import home, contacts, ProductListView, ProductDetailView, ProductCreatelView, ProductUpdatelView, \
    ProductDeleteView

app_name = MainConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product'),
    path('product/create/', ProductCreatelView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', ProductUpdatelView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserVerificationView, delete

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verification/', UserVerificationView.as_view(), name='verification'),
    path('resert/', delete, name='resert'),
]

main/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.name}({self.description})'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='main/',verbose_name='изображение (превью)', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена за покупку')
    create_data = models.DateTimeField(verbose_name='Дата создания', **NULLABLE)
    change_data = models.DateTimeField(verbose_name='Дата последнего изменения', **NULLABLE)

    def __str__(self):
        return f'{self.name}({self.description}, {self.category}, {self.cost})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

class Version(models.Model):
    version_number = models.IntegerField(verbose_name='Номер версии', unique=True)
    version_name = models.CharField(max_length=100, verbose_name='Название версии')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')


    is_active = models.BooleanField(default=True, verbose_name='Активная версия')


    def __str__(self):
        return f'{self.version_number} ({self.product}, {self.version_name})'

    class Meta:
        verbose_name = 'версию'
        verbose_name_plural = 'версии'

main/forms.py
from django import forms

from main.models import Product, Version

class StyleForMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class ProductForm(StyleForMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')
        cleaned_list = ['Казино', 'Криптовалюта', 'Крипта', 'Биржа', 'Дешево', 'Бесплатно', 'Обман', 'Полиция', 'Радар']
        if cleaned_data in cleaned_list:
            raise forms.ValidationError('Товар с таким наименованием запрещен')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        cleaned_list = ['Казино', 'Криптовалюта', 'Крипта', 'Биржа', 'Дешево', 'Бесплатно', 'Обман', 'Полиция', 'Радар']
        if cleaned_data in cleaned_list:
            raise forms.ValidationError('Товар с таким описанием запрещен')

        return cleaned_data

class VersionForm(StyleForMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

main/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from main.forms import ProductForm, VersionForm
from main.models import Product, Version


def home(request):
    context = {
        'object_list': Product.objects.all(),
        'title': 'Skystore',
        'title_comments': 'Skystore - это отличный вариант выбора товара на любой вкус!'
    }
    return render(request, 'main/home.html', context)

def contacts(request):
    if request.method == "POST":
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}): {message}')
    return render(request, 'main/contacts.html')


class ProductListView(ListView):
    model = Product
    template_name = 'main/home.html'

class ProductDetailView(DetailView):
    model = Product
    template_name = 'main/product.html'

class ProductCreatelView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'main/product_form.html'

    def get_success_url(self):
        return reverse('main:home')

class ProductUpdatelView(UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('main:product', args=[self.kwargs.get('pk')])
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context_data['formset'] = formset

        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)




class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('main:home')

main/templates/main/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
        <a class="p-2 btn btn-outline-primary" href='/list/'>Блоги</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'main:product_create' %}">Создать новый продукт </a>
    </nav>,
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{title}}</h1>
    <p class="lead">{{title_comments}}</p>
</div>

<div class="container">

    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

main/templates/main/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Комментарий" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

main/templates/main/home.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="row text-center">
        {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{object.cost}} ₽</h1>
                        <img class="card-img-top"
                             src="{{ object.image|mymedia }}"
                             alt="Card image cap">
                        </ul>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{object.description|slice:":10"}}...</li>
                            <li>{{object.category}}</li>
                        </ul>
                        <a href="{% url 'main:product' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Купить</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

main/templates/main/product.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="row text-center">

        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal">{{object.name}}</h3>
                    <h4 class="my-0 font-weight-normal">{{object.description}}</h4>
                </div>
                <img class="card-img-top"
                    src="{{ object.image|mymedia }}"
                    alt="Card image cap">
                </ul>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>{{object.category}}</li>
                </ul>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{object.cost}} ₽</h1>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                    <a href="{% url 'main:product_update' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Изменить</a>
                    <a href="{% url 'main:product_delete' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

main/templates/main/product_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Действительно удалить продукт: {{ object.name }}?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a href="{% url 'main:home' %}" class="btn btn-success">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{%  endblock %}

main/templates/main/product_form.html
{% extends 'main/base.html' %}

{% block content %}

<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>

            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                        <hr>
                    {% endfor %}
                 </form>
            </div>
        </div>
    </div>
 </form>

{%  endblock %}

main/templates/main/version_form.html
{% extends 'main/base.html' %}
{% csrf_token %}
{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Создать</button>
                </form>
            </div>
        </div>
    </div>
</div>
{%  endblock %}